In [1]:
import numpy as np
import pandas as pd

In [2]:
prova = np.array([1,2,3])

In [3]:
prova

array([1, 2, 3])

In [4]:
update = np.empty((3,3))

In [5]:
update = np.append(update, prova)

In [6]:
update

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 8.75484324e-321, 1.11261027e-306, 1.11261502e-306,
       1.42410839e-306, 1.00000000e+000, 2.00000000e+000, 3.00000000e+000])

In [7]:
from sklearn import datasets

In [8]:
iris = datasets.load_iris()

In [9]:
X = iris.data[:,:2]
X = pd.DataFrame(X)

In [10]:
X.to_numpy(dtype = np.float32)

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [11]:
from sklearn.model

SyntaxError: invalid syntax (<ipython-input-11-73a5a0c4b3e6>, line 1)

In [ ]:
for i in X.index:
    print(i)