# Niural Test

In [1]:
from niural import Niural
import pandas as pd
from sklearn import datasets
import numpy as np

In [2]:
iris = datasets.load_iris()

X = iris.data[:, :2]  # we only take the first two features.
y = iris.target
X = pd.DataFrame(X[y != 2])
y = pd.DataFrame(y[y != 2])

In [3]:
niural = Niural(20, 0.01, 200, [3])

#niural.prova()
niural.fit(X,y)

Weights
[[0.8215141  0.55817017 0.44939763]
 [0.42212561 0.92486295 0.41435608]
 [0.86465245 0.74513351 0.34659637]]
-------------------------
[[0.55038522 0.69847553 0.52034839 0.15505628]]
-------------------------
Prediction is:
[array([5.1, 3.5]), array([0.99473332, 0.99862671, 0.99720722]), array([0.87207588])]
Looping over 1
-------------------------
[[[0.0025145772117586393, 0.0006582425439083701, 0.001336728971143442], [0.0031911661081771864, 0.0008353536679081085, 0.0016963981732532126], [0.002377346213199872, 0.0006223194944303096, 0.0012637780787808433], [0.0007084147054556987, 0.00018544218713217872, 0.0003765875455875936]], [0.8720758770944249]]


In [4]:
def sigmoid(number):
    return 1/(1 + np.exp(-number))

In [5]:
theta1 = niural.weights[0]
theta2 = niural.weights[1]

In [6]:
trainData = X.iloc[0,:].to_numpy()
trainData = np.insert(trainData,0,1)
trainData

array([1. , 5.1, 3.5])

In [7]:
z1 = np.dot(trainData,np.transpose(theta1))
z1 = sigmoid(z1)
a1 = np.insert(z1,0,1)
a1

array([1.        , 0.99473332, 0.99862671, 0.99720722])

In [8]:
z2 = np.dot(a1,np.transpose(theta2))
z2

array([1.91943914])

In [9]:
a2 = sigmoid(z2)
a2

array([0.87207588])

In [10]:
err2 = a2 - y[0][0]
err2

array([0.87207588])

In [11]:
0,1,2


(0, 1, 2)

In [12]:
err1 = np.dot(np.transpose(theta2),err2) * (a1 * (1 - a1))
err1

array([0.        , 0.00319117, 0.00062232, 0.00037659])

In [30]:
a = np.array([5.1,3.5])
a_history = [a]
a = np.insert(a,0,1)
print(a)
print(theta1)
z = np.dot(a,np.transpose(theta1))

[1.  5.1 3.5]
[[0.8215141  0.55817017 0.44939763]
 [0.42212561 0.92486295 0.41435608]
 [0.86465245 0.74513351 0.34659637]]


In [13]:
#classe1,classe2, classe3
y_true = np.array([1,0,0])
error_output = [0.7,0.1,0.2] - y_true
error_output

array([-0.3,  0.1,  0.2])

In [14]:
for i in range(5,0):
    print(i)

In [15]:
errors = np.array(np.array([0.8667]) - np.array([1]))
errors2 = np.concatenate(([1,2], errors.tolist()),axis=0)
errors2.tolist()

[1.0, 2.0, -0.13329999999999997]

In [16]:
errors = [(np.array([0.73271106]) - 0).tolist()]
errors

[[0.73271106]]

In [17]:
i = len(niural.hidden_layer)
i

1

In [31]:
np.transpose(niural.weights[1]) 

array([[0.55038522],
       [0.69847553],
       [0.52034839],
       [0.15505628]])

In [34]:
new_a1 = np.array([0.99473332, 0.99862671, 0.99720722])
term = (new_a1 * (1 - new_a1))

In [36]:
np.multiply(np.dot(np.transpose(niural.weights[1]),np.array([errors[0]])),term)

array([[0.00211273, 0.00055305, 0.00112311],
       [0.00268119, 0.00070186, 0.0014253 ],
       [0.00199743, 0.00052287, 0.00106182],
       [0.0005952 , 0.00015581, 0.00031641]])

In [ ]:
np.array([errors[0]]).shape

In [ ]:
np.array([errors[0]]).shape