# Niural Test

In [1]:
from niural import Niural
import pandas as pd
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

X = iris.data[:, :2]  # we only take the first two features.
y = iris.target
X = pd.DataFrame(X[y != 2])
y = pd.DataFrame(y[y != 2])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [3]:
y

0
0   0
1   0
2   0
3   0
4   0
.. ..
95  1
96  1
97  1
98  1
99  1

[100 rows x 1 columns]

In [4]:
niural = Niural(20, 0.01, 200, [3])

#niural.prova()
niural.fit(X_train,y_train)

Index 84
Index 68
Index 60
Index 71
Index 99
Index 4
Index 62
Index 49
Index 79
Index 97
Index 16
Index 35
Index 40
Index 64
Index 93
Index 56
Index 48
Index 39
Index 57
Index 34
Index 3
Index 21
Index 26
Index 88
Index 92
Index 0
Index 94
Index 55
Index 51
Index 82
Index 20
Index 2
Index 38
Index 47
Index 6
Index 18
Index 75
Index 85
Index 13
Index 30
Index 96
Index 29
Index 23
Index 90
Index 46
Index 91
Index 66
Index 10
Index 50
Index 42
Index 41
Index 95
Index 69
Index 33
Index 98
Index 32
Index 31
Index 7
Index 78
Index 89
Index 59
Index 74
Index 8
Index 72
Index 9
Index 43
Index 63
Index 36
Index 44
Index 87
Index 84
Index 68
Index 60
Index 71
Index 99
Index 4
Index 62
Index 49
Index 79
Index 97
Index 16
Index 35
Index 40
Index 64
Index 93
Index 56
Index 48
Index 39
Index 57
Index 34
Index 3
Index 21
Index 26
Index 88
Index 92
Index 0
Index 94
Index 55
Index 51
Index 82
Index 20
Index 2
Index 38
Index 47
Index 6
Index 18
Index 75
Index 85
Index 13
Index 30
Index 96
Index 29
Index

Index 41
Index 95
Index 69
Index 33
Index 98
Index 32
Index 31
Index 7
Index 78
Index 89
Index 59
Index 74
Index 8
Index 72
Index 9
Index 43
Index 63
Index 36
Index 44
Index 87
Index 84
Index 68
Index 60
Index 71
Index 99
Index 4
Index 62
Index 49
Index 79
Index 97
Index 16
Index 35
Index 40
Index 64
Index 93
Index 56
Index 48
Index 39
Index 57
Index 34
Index 3
Index 21
Index 26
Index 88
Index 92
Index 0
Index 94
Index 55
Index 51
Index 82
Index 20
Index 2
Index 38
Index 47
Index 6
Index 18
Index 75
Index 85
Index 13
Index 30
Index 96
Index 29
Index 23
Index 90
Index 46
Index 91
Index 66
Index 10
Index 50
Index 42
Index 41
Index 95
Index 69
Index 33
Index 98
Index 32
Index 31
Index 7
Index 78
Index 89
Index 59
Index 74
Index 8
Index 72
Index 9
Index 43
Index 63
Index 36
Index 44
Index 87
Index 84
Index 68
Index 60
Index 71
Index 99
Index 4
Index 62
Index 49
Index 79
Index 97
Index 16
Index 35
Index 40
Index 64
Index 93
Index 56
Index 48
Index 39
Index 57
Index 34
Index 3
Index 21
Index

In [38]:
#sigmoid(np.dot(niural.weights[0], np.array([[1.0], [6.3], [2.5]])))
y_test

0
65  1
53  1
25  0
67  1
77  1
52  1
11  0
45  0
81  1
37  0
54  1
12  0
28  0
80  1
1   0
19  0
86  1
5   0
14  0
76  1
24  0
22  0
17  0
73  1
83  1
27  0
61  1
15  0
70  1
58  1

In [6]:
y_pred = niural.predict(X_test)
y_pred

65 : [array([[6.7],
       [3.1]]), array([[0.32862778],
       [0.95738829],
       [0.05190693]]), array([[0.4898578]])] 
------------------

0.4898578036533009
53 : [array([[5.5],
       [2.3]]), array([[0.41558784],
       [0.92129203],
       [0.08946347]]), array([[0.50214444]])] 
------------------

0.5021444436252727
25 : [array([[5.],
       [3.]]), array([[0.37053514],
       [0.94901269],
       [0.08605548]]), array([[0.49760276]])] 
------------------

0.49760276012234866
67 : [array([[5.8],
       [2.7]]), array([[0.37730896],
       [0.94077717],
       [0.0743437 ]]), array([[0.49678814]])] 
------------------

0.4967881365898012
77 : [array([[6.7],
       [3. ]]), array([[0.3360277 ],
       [0.95438814],
       [0.05328719]]), array([[0.49065474]])] 
------------------

0.49065473523450853
52 : [array([[6.9],
       [3.1]]), array([[0.3247171 ],
       [0.95794659],
       [0.04900752]]), array([[0.48918269]])] 
------------------

0.4891826936460239
11 : [array([[4.8

[0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [7]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(y_true = y_test, y_pred = y_pred)
#print(conf_mat)
tn, fp, fn, tp = conf_mat.ravel()
print("\tActual values")
print("\t1\t0")
print("1|\t",tp,"\t",fp)
print("0|\t",fn,"\t",tn)
print("\n1 = fraudulent, 0 = true job posting")

	Actual values
	1	0
1|	 3 	 0
0|	 12 	 15

1 = fraudulent, 0 = true job posting


In [8]:
gradients= np.zeros(niural.weights[0].shape)
gradients

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
niural.a_history[-1][0][0]

0.4955689211374363

In [10]:
a1 = np.array([[1.1], [5.1], [3.5]])

In [11]:
error1 = niural.train_errors[0][0]
error1

[-0.03201268684183616]

In [12]:
prova = error1 * a1
prova = prova.flatten()
prova

array([-0.03521396, -0.1632647 , -0.1120444 ])

In [13]:
update = np.array([])

In [14]:
ei = np.concatenate((update, prova))
ei = np.concatenate((ei, prova))
ei = np.concatenate((ei, prova))

In [15]:
ei

array([-0.03521396, -0.1632647 , -0.1120444 , -0.03521396, -0.1632647 ,
       -0.1120444 , -0.03521396, -0.1632647 , -0.1120444 ])

In [16]:
ei.reshape(niural.weights[0].shape)

array([[-0.03521396, -0.1632647 , -0.1120444 ],
       [-0.03521396, -0.1632647 , -0.1120444 ],
       [-0.03521396, -0.1632647 , -0.1120444 ]])

In [17]:
np.array([[1,2], [3, 3]]) - np.array([[1,1], [1, 1]])

array([[0, 1],
       [2, 2]])

In [18]:
def sigmoid(number):
    return 1/(1 + np.exp(-number))

In [19]:
theta1 = niural.weights[0]
theta2 = niural.weights[1]

In [20]:
trainData = X.iloc[0,:].to_numpy()
trainData = np.insert(trainData,0,1)
trainData

array([1. , 5.1, 3.5])

In [21]:
z1 = np.dot(trainData,np.transpose(theta1))
z1 = sigmoid(z1)
a1 = np.insert(z1,0,1)
a1

array([1.        , 0.33057911, 0.96396686, 0.07367602])

In [22]:
z2 = np.dot(a1,np.transpose(theta2))
z2

array([-0.02928262])

In [23]:
a2 = sigmoid(z2)
a2

array([0.49267987])

In [24]:
err2 = a2 - y[0][0]
err2

array([0.49267987])

In [25]:
0,1,2


(0, 1, 2)

In [26]:
err1 = np.dot(np.transpose(theta2),err2) * (a1 * (1 - a1))
err1

array([-0.        ,  0.02917358, -0.00263433,  0.01819881])

In [27]:
a = np.array([5.1,3.5])
a_history = [a]
a = np.insert(a,0,1)
print(a)
print(theta1)
z = np.dot(a,np.transpose(theta1))

[1.  5.1 3.5]
[[ 0.91509743 -0.08889713 -0.33351116]
 [ 0.44423901  0.06885722  0.71177342]
 [-0.01845981 -0.30266009 -0.27700583]]


In [28]:
#classe1,classe2, classe3
y_true = np.array([1,0,0])
error_output = [0.7,0.1,0.2] - y_true
error_output

array([-0.3,  0.1,  0.2])

In [29]:
for i in range(5,0):
    print(i)

In [30]:
errors = np.array(np.array([0.8667]) - np.array([1]))
errors2 = np.concatenate(([1,2], errors.tolist()),axis=0)
errors2.tolist()

[1.0, 2.0, -0.13329999999999997]

In [31]:
errors = [(np.array([0.73271106]) - 0).tolist()]
errors

[[0.73271106]]

In [32]:
i = len(niural.hidden_layer)
i

1

In [33]:
np.transpose(niural.weights[1]) 

array([[-0.00922505],
       [ 0.26757787],
       [-0.15393636],
       [ 0.54123893]])

In [34]:
new_a1 = np.array([0.99473332, 0.99862671, 0.99720722])
term = (new_a1 * (1 - new_a1))

In [35]:
np.multiply(np.dot(np.transpose(niural.weights[1]),np.array([errors[0]])),term)

array([[-3.54115688e-05, -9.26972832e-06, -1.88245113e-05],
       [ 1.02713266e-03,  2.68873734e-04,  5.46015640e-04],
       [-5.90904858e-04, -1.54681865e-04, -3.14120372e-04],
       [ 2.07761643e-03,  5.43860114e-04,  1.10444454e-03]])

In [36]:
np.array([errors[0]]).shape

(1, 1)

In [37]:
np.array([errors[0]]).shape

(1, 1)